config/routes.rb
Rails.application.routes.draw do
  resources :collections
  resources :pictures
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ApplicationRecord
    has_many :pictures, :dependent => :destroy
end

app/models/picture.rb
class Picture < ApplicationRecord
    belongs_to :collection

    has_attached_file :image,
    :path => ":rails_root/public/images/:id/:filename",
    :url  => "/images/:id/:filename"

    do_not_validate_attachment_file_type :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
    before_action :find_collection, only: [:show, :edit, :update, :destroy]

    def index
        @collection = Collection.all
    end

    def new
        @collection = Collection.new
    end

    def create
        @collection = Collection.new collection_params

        if @collection.save
            if params[:images]

                params[:images].each { |image|
                  @collection.pictures.create(image: image)
                }
            end

            redirect_to @collection, notice: "Your Collection saved."
        else 
            render 'new', notice: "Your Collection was not saved successfully."
        end
    end

    def edit
    end

    def update
        if @collection.update collection_params
            if params[:images]

                params[:images].each { |image|
                    @collection.pictures.create(image: image)
                }
            end

            redirect_to @collection, notice: "Your Collection was successfully updated."
        else
            render 'edit', notice: "your Collection was not successfully updated. Try again."
        end
    end

    def show
        @pictures = @collection.pictures
    end

    def destroy
        @collection.destroy
        redirect_to collections_path
    end

    private

    def collection_params
        params.require(:collection).permit(:title, :description, :pictures)
    end

    def find_collection
        @collection = Collection.find(params[:id])
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
    before_action :find_picture, only: [:show, :edit, :update, :destroy]

    def index
        @collection = Collection.find(params[:collection_id])

        @pictures = @collection.pictures
    end

    def show
    end

    def new 
        @collection = Collection.find(params[:collection_id])
        @picture = @collection.pictures.build
    end

    def edit
    end

    def create
        @picture = Picture.new(params[:picture])
    end

    def update
        @collection = Collection.find(params[:collection_id])
    end

    def destroy
        @picture.destroy
    end

    private
    
      def picture_params
        params.require(:picture).permit(:gallery_id, :image)
      end

      def find_picture
        @picture = Picture.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/collections/_form.html.erb
<%= form_for @collection, :html => { multipart: true } do |form| %>
    <% if @collection.errors.any? %>
        <h2><%= pluralize(@collection.errors.count, "error") %> prevented this post from saving.</h2>

        <ul>
            <% @collection.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>        
        </ul>
    <% end %>

    <%= form.label :title %> <br>
    <%= form.text_field :title %>

    <br>
    <br>

    <%= form.label :description %> <br>
    <%= form.text_area :description %>

    <br>
    <br>

    <div class="control-group">
        <%= form.label :pictures, :class => 'control-label' %>
        <div class="controls">
        <!-- The magic is coming ...look at my eyes....shazammmm -->
        <!-- Use HTML5 multiple attribute to enable multiple selection
            and pass back to controller all files as an array, ready 
            for paperclip!!
            file_field_tag, since images is not a gallery attribute
        -->
        <%= file_field_tag "images[]", type: :file, multiple: true %>
        </div>
    </div>

    <div class="form-actions">
        <%= form.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    collections_path, :class => 'btn btn-mini' %>
    </div>

<% end %>

app/views/collections/edit.html.erb
<h1>Edit Collection</h1>


<%= render 'form' %>

app/views/collections/index.html.erb
<h1>Hello World!</h1>

<p>Collections index - collections page</p>

app/views/collections/new.html.erb
<h1>New Collection</h1>

<%= render 'form' %>

app/views/collections/show.html.erb
<%= @collection.title %>
<br>
<%= @collection.description %>

<br><br>

<%= link_to 'Back', collections_path, :class => 'btn btn-mini'  %>
<%= link_to "Edit", edit_collection_path(@collection) %>
<%= link_to "Delete", collection_path(@collection), method: :delete, data: { confirm: "Are you sure you want to delete this Collection?"} %>

<h2>Pictures</h2>
</div>

<div class="row">
  <ul class="thumbnails files">
<% unless @pictures.empty? %>
  <% @pictures.each do |pic| %>
    <li class="span3" id="picture_<%= pic.id %>">
    <div class="thumbnail">
      <%= image_tag pic.image.url %>
      <div class="caption">
        <p style="text-align: center;">
        <%= link_to "Edit picture", picture_path(pic) %>

        <%=
          link_to "Delete picture", pic,
            :data => { :confirm => "Are you sure?" },
            :method => :delete
          %>

        </p>
      </div>
    </div>
    </li>
  <% end %>
<% end %>
</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photoapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pictures/edit.html.erb
<h1>Edit Picture</h1>


<%= render 'form' %>

app/views/pictures/show.html.erb
<%- model_class = @picture.class -%>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= @picture.image %></dd>
  <dt><strong><%= model_class.human_attribute_name(:collection_id) %>:</strong></dt>
  <dd><%= @picture.collection_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              pictures_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_picture_path(@picture), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              picture_path(@picture),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>